Add ARN validate webhook (#11)
* Add webhook scaffolding

* Implement validation logic

* Create manifests

* Validate all ARNs before returing an error

* Add sample with invalid arns

* Add commands for loading images

* Setup webhook in kustomize

* Add features

* Add Validating webhook test

* Fix linting issue

* Add release

* Install cert-manager

* Use default kind name

* Add cluster variable

diff --git a/.github/workflows/test-kustomize.yaml b/.github/workflows/test-kustomize.yaml
--- a/.github/workflows/test-kustomize.yaml
+++ b/.github/workflows/test-kustomize.yaml
@@ -12,6 +12,7 @@ jobs:
     runs-on: ubuntu-latest
     env:
       IMG: controller:kind
+      CLUSTER: kind
     steps:
       - uses: actions/checkout@v2.4.0
 
@@ -22,19 +23,36 @@ jobs:
       - name: Create kind cluster
         uses: helm/kind-action@v1.2.0
         with:
-          cluster_name: kind
+          cluster_name: ${{ env.CLUSTER }}
+
+      - name: Install cert-manager
+        run: kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml
 
       - name: Build and push
         run: make docker-build
 
       - name: Push the image to Kind cluster
-        run: kind load docker-image controller:kind
+        run: make kind-load
 
       - name: Install CRDs
         run: make install
 
       - name: Install manifests
         run: make deploy
+
+      - name: Wait for controller to be ready
+        run: |
+          count=0
+          until [ '1' == "$( kubectl get deploy aws-auth-manager-controller-manager -n aws-auth-manager-system -o json | jq 'try .status.readyReplicas' )" ]; do
+            echo -n '.'
+            sleep 5
+            count=$((count + 1))
+            if [[ ${count} -eq 6 ]]; then
+              echo ' No more retries left!'
+              exit 1
+            fi
+          done
+          echo ' done'
 
       - name: Deploy example AWSAuthItem
         run: kubectl apply -f config/samples/awsauthitem.yaml
@@ -53,3 +71,15 @@ jobs:
             fi
           done
           echo ' done'
+
+      - name: Test ARN validation webhook
+        run: |
+          output=$(kubectl apply -f config/samples/invalid_arn.yaml || true)
+          substring="The AWSAuthItem \"awsauthitem-invalid\" is invalid"
+          if [ -z "${output##*$reqsubstr*}" ]; then
+            echo 'Invalid AWSAuthItem failed validation'
+            exit 0
+          else
+            echo 'Validation Webhook not working as expected'
+            exit 1
+          fi
